/* GENERATED by tools/gen_vectors.py -- do not edit.
 * SPDX-License-Identifier: 0BSD */
#ifndef MIDI_VECTORS_H
#define MIDI_VECTORS_H
#include <stdint.h>

typedef struct { const char *name; const uint8_t *bytes;
                 uint32_t len; } midi_vector;
extern const midi_vector midi_vectors[];

extern const uint8_t midi_demo[];
extern const uint32_t midi_demo_len;
extern const uint8_t midi_bank[];
extern const uint32_t midi_bank_len;
extern const uint8_t midi_bad[];
extern const uint32_t midi_bad_len;

#endif
