#!/usr/bin/env python3
"""gen_vectors.py - compile port/host's MIDI test vectors into the image.

The bare-metal image has no filesystem to read a stream from, so the streams
are linked into .rodata. They are NOT a new set of test data: the three
generators below are copied verbatim from the places workstream D already
asserts against, so that the host, the qemu-user armv7 run and the bare-metal
run are answering questions about the same bytes.

  demo  port/host/main.c, the built-in DEMO[] array
  bank  port/host/test.sh case 2: 64 x 254-byte patch sysexes (about 16 kB of
        wire, 5.25 s at 31250 baud) with notes and Active Sensing interleaved
  bad   port/host/test.sh case 3: orphan data bytes, an unterminated sysex,
        and a sysex larger than the 32 kB cap

Regenerate with:  make vectors     (or python3 tools/gen_vectors.py src/)
SPDX-License-Identifier: 0BSD
"""
import sys, os

# --- port/host/main.c DEMO[] ------------------------------------------------
def demo():
    out = bytearray([0x90, 60, 100, 64, 100, 67, 100, 72, 100])
    out += bytes([0xF0, 0x41, 0x10, 0x16, 0x12, 0x20, 0x00, 0x00])
    out += b'HELLO MT-32         '
    out += bytes([0x00, 0xF7])
    out += bytes([0xFE])
    out += bytes([0x80, 60, 0, 64, 0, 67, 0, 72, 0])
    return bytes(out)

# --- port/host/test.sh case 2 ----------------------------------------------
def bank():
    def sysex(addr, data):
        body = list(addr) + list(data)
        return bytes([0xF0, 0x41, 0x10, 0x16, 0x12]) + bytes(body) + \
               bytes([(-sum(body)) & 0x7f, 0xF7])
    out = bytearray([0x90, 60, 100, 64, 100, 67, 100])
    for i in range(64):
        out += sysex((0x08, (i * 2) & 0x7f, 0x00),
                     bytes([(j * 7 + i) & 0x7f for j in range(246)]))
        if i % 8 == 0:
            out += bytes([0xFE, 72 + (i % 5), 90])
    out += bytes([0xB0, 123, 0])
    return bytes(out)

# --- port/host/test.sh case 3 ----------------------------------------------
def bad():
    b = bytearray([40, 50, 60])
    b += bytes([0xF0, 0x41, 0x10, 0x16, 0x12]) + bytes(100)
    b += bytes([0x90, 60, 100])
    b += bytes([0xF0]) + bytes([0x7f] * 40000) + bytes([0xF7])
    b += bytes([0x80, 60, 0])
    return bytes(b)

def emit(f, name, data):
    f.write("const uint8_t midi_%s[] = {" % name)
    for i, v in enumerate(data):
        f.write("\n   " if i % 16 == 0 else " ")
        f.write("0x%02x," % v)
    f.write("\n};\nconst uint32_t midi_%s_len = %u;\n\n" % (name, len(data)))

def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "src"
    streams = [("demo", demo()), ("bank", bank()), ("bad", bad())]
    with open(os.path.join(outdir, "midi_vectors.c"), "w") as f:
        f.write("/* GENERATED by tools/gen_vectors.py -- do not edit.\n"
                " * The same bytes port/host/test.sh asserts against.\n"
                " * SPDX-License-Identifier: 0BSD */\n"
                '#include "midi_vectors.h"\n\n')
        for n, d in streams:
            emit(f, n, d)
        f.write("const midi_vector midi_vectors[] = {\n")
        for n, d in streams:
            f.write('    { "%s", midi_%s, %u },\n' % (n, n, len(d)))
        f.write("    { 0, 0, 0 }\n};\n")
    with open(os.path.join(outdir, "midi_vectors.h"), "w") as f:
        f.write("/* GENERATED by tools/gen_vectors.py -- do not edit.\n"
                " * SPDX-License-Identifier: 0BSD */\n"
                "#ifndef MIDI_VECTORS_H\n#define MIDI_VECTORS_H\n"
                "#include <stdint.h>\n\n"
                "typedef struct { const char *name; const uint8_t *bytes;\n"
                "                 uint32_t len; } midi_vector;\n"
                "extern const midi_vector midi_vectors[];\n\n")
        for n, d in streams:
            f.write("extern const uint8_t midi_%s[];\n"
                    "extern const uint32_t midi_%s_len;\n" % (n, n))
        f.write("\n#endif\n")
    for n, d in streams:
        print("%-5s %6d bytes  (%.2f s of wire at 31250 baud)"
              % (n, len(d), len(d) * 10.0 / 31250.0))

main()
